apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 3
  selector:
    app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        ver: "1.0"
    spec:
      containers:
      - name: simple-pod
        image:  bpraveen18/tomjen:latest
        ports:
        - containerPort: 8080
